### ISSUE TITLE
Successful Payment Leads to 404 on /billing Page

### ISSUE THREAD

**Issue by iRajatDas** [d-ivashchuk/cascade#4]
# Description:
After completing a successful payment, the user is redirected to the "/billing" page, but this leads to a 404 error page. This issue disrupts the user experience and prevents them from accessing relevant billing information post-payment.

### Initiate a payment process.
- Successfully complete the payment.
- Observe the redirection to "/billing".
- Encounter the 404 error page.

### Expected Behavior:
After a successful payment, users should be redirected to the appropriate billing page where they can view relevant information without encountering a 404 error.

**Comment by d-ivashchuk** [comment]
Good one, thanks!
